apiVersion: batch/v1
kind: Job
metadata:
  name: pysedm
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: ztf-worker-3
      containers:
      - name: pysedm
        image: ztfsedm/ztf
        imagePullPolicy: Always
        command: ["sh",  "/config-run/run.sh"]
        # command: ["tail",  "-f", "/dev/null"]
        volumeMounts:
          - name: config-run
            mountPath: /config-run
          - mountPath: /mnt/data
            name: ztf-data
      restartPolicy: Never
      volumes:
        - name: config-run
          configMap:
            name: config-run
        - name: ztf-data 
          hostPath:
             path: /mnt/data
