apiVersion: batch/v1
kind: Job
metadata:
  name: pysedm
spec:
  template:
    spec:
      containers:
      - name: pysedm
        image: ztfsedm/ztf
        imagePullPolicy: Always
        command: ["sh",  "/config-run/run.sh"]
        # command: ["tail",  "-f", "/dev/null"]
        volumeMounts:
          - name: config-run
            mountPath: /config-run
      restartPolicy: Never
      volumes:
        - name: config-run
          configMap:
            name: config-run
