apiVersion: batch/v1
kind: Job
metadata:
  name: pysedm
spec:
  template:
    spec:
      containers:
      - name: pysedm
        image: ztfsedm/ztf
        command: ["sh",  "/config-run/run.sh"]
        volumeMounts:
          - name: config-run
            mountPath: /config-run
      restartPolicy: Never
  backoffLimit: 4
  volumes:
    - configMap:
      name: config-run
